// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edgzdncozxgfxsbgeayy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkZ3pkbmNvenhnZnhzYmdlYXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMjY5MTQsImV4cCI6MjA3NDcwMjkxNH0.RLzAmvzoymFEaq9h4cS1yEspiY6YPRW6N6BgWwCH54o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});